require('majid.plugins.treesitter')
require('majid.plugins.mason')
require('majid.plugins.cmp')
require('majid.plugins.lualine')
require('majid.plugins.telescope')
require('majid.plugins.dashboard')
require('majid.plugins.colorscheme')
